annotate/annotate/urls.py
"""URLs for the annotate project."""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout
from django.contrib.sitemaps import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import cache_page
from django.views.defaults import page_not_found, server_error
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog
from django.views.static import serve

from django_libs.views import UpdateSessionAJAXView

from .views import AnnotateLoginView, AnnotateSignupView, ContentTemplateView


LOGOUT_REDIRECT_URL = getattr(settings, 'ACCOUNT_LOGOUT_REDIRECT_URL', '/')

admin.autodiscover()

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG is False and settings.SANDBOX is True:
    # If you want to set DEBUG=False on your local machine, Django would no
    # longer serve static files and you would have to setup Apache or Nginx.
    # This hack allows Django to serve staticfiles (which is slow and insecure)
    urlpatterns += [
        url(r'^404/$', page_not_found),
        url(r'^500/$', server_error),
        url(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    ]

sitemaps = {
    # 'cmspages': CMSSitemap,
}


@cache_page(60 * 60 * 4)
def cached_javascript_catalog(request, domain='djangojs', packages={
        'packages': ('annotate', )}):
    return javascript_catalog(request, domain, packages)

urlpatterns += [
    url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', views.sitemap, {
        'sitemaps': sitemaps}),
    url(r'^jsi18n.js$', cached_javascript_catalog, name='javascript_catalog'),
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^admin-.+/', include('admin_honeypot.urls',
                               namespace='admin_honeypot')),
    url(r'^accounts/login/$', AnnotateLoginView.as_view(),
        name='account_login'),
    url(r'^accounts/signup/$', AnnotateSignupView.as_view(),
        name='account_signup'),
    url(r'^accounts/logout/$', logout,
        {'next_page': LOGOUT_REDIRECT_URL}, name='account_logout'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^profile/', include('profiles.urls')),
    url(r'^support/', include('contact_form.urls')),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^update-session/$', UpdateSessionAJAXView.as_view(),
        name='update_session'),
    url(r'^about/(?P<template>\w+)/$', ContentTemplateView.as_view(),
        name='about'),
    url(r'^$', TemplateView.as_view(template_name='content/home.html')),
]

annotate/projects/urls.py
"""URLs for the projects app."""
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^invitations/(?P<pk>\d+)/decline/$',
        views.InvitationDeclineView.as_view(),
        name='invitation_decline'),
    url(r'^invitations/(?P<pk>\d+)/accept/$',
        views.InvitationAcceptView.as_view(),
        name='invitation_accept'),
    url(r'^invitations/$', views.InvitationListView.as_view(),
        name='invitation_list'),
    url(r'^(?P<project_pk>\d+)/invitations/$',
        views.InvitationCreateView.as_view(),
        name='invitation_create'),
    url(r'^file/annotation/(?P<pk>\d+)/delete/$',
        views.AnnotationDeleteView.as_view(), name='annotation_delete'),
    url(r'^file/(?P<file_pk>\d+)/label/(?P<label_pk>\d+)/$',
        views.AnnotationCreateView.as_view(), name='annotation_create'),
    url(r'^file/(?P<pk>\d+)/label/$', views.FileLabelView.as_view(),
        name='file_label'),
    url(r'^file/(?P<pk>\d+)/delete/$', views.FileDeleteView.as_view(),
        name='file_delete'),
    url(r'^(?P<project_pk>\d+)/file/create/$', views.FileCreateView.as_view(),
        name='file_create'),
    url(r'^(?P<pk>\d+)/story/$', views.ProjectStoryView.as_view(),
        name='project_story'),
    url(r'^(?P<pk>\d+)/info/$', views.ProjectInfoView.as_view(),
        name='project_info'),
    url(r'^label/(?P<pk>\d+)/delete/$', views.LabelDeleteView.as_view(),
        name='label_delete'),
    url(r'^label/(?P<pk>\d+)/update/$', views.LabelUpdateView.as_view(),
        name='label_update'),
    url(r'^(?P<pk>\d+)/label/create/$', views.LabelCreateView.as_view(),
        name='label_create'),
    url(r'^(?P<pk>\d+)/files/$', views.FileListJSONView.as_view(),
        name='file_json'),
    url(r'^(?P<pk>\d+)/$', views.ProjectDetailView.as_view(),
        name='project_detail'),
    url(r'^create/$', views.ProjectCreateView.as_view(),
        name='project_create'),
]

annotate/projects/models.py
"""Models for the project view."""
import re

from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Project(models.Model):
    """
    A project contains documents and labels.

    :name: Name of the project.
    :owner: User, who owns this project.
    :type: Type of the project.
    :deadline: Project deadline.
    :purpose: Purpose of the project.
    :description: Long and detailed project description.
    :contributors: Users, who contribute to this project.

    """
    name = models.CharField(
        max_length=256,
        verbose_name=_('Name'),
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Owner'),
        related_name='projects',
    )

    type = models.CharField(
        max_length=256,
        verbose_name=_('Project type'),
        choices=(
            ('document', _('Document labelling')),
            ('edge', _('Edge labelling')),
            ('span', _('Span labelling')),
        )
    )

    deadline = models.DateField(
        blank=True, null=True,
        verbose_name=_('Deadline'),
    )

    purpose = models.CharField(
        max_length=256,
        verbose_name=_('Purpose'),
        choices=(
            ('pos', _('POS tagging')),
            ('sentiment', _('Sentiment')),
            ('dependency', _('Dependency')),
        )
    )

    description = models.TextField(
        max_length=2048,
        verbose_name=_('Description'),
    )

    contributors = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Contributors'),
        related_name='projects_contributed',
        blank=True,
    )

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')
        ordering = ['name']

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class File(models.Model):
    """
    File object, which can be assigned to a project.

    :file: File instance.
    :project: Project, the file should be assigned to.
    """
    file = models.FileField(
        verbose_name=_('File'),
        upload_to="project_files",
    )

    project = models.ForeignKey(
        'projects.Project',
        verbose_name=_('Project'),
        related_name='files',
    )

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')
        ordering = ['-pk']

    def __str__(self):
        return self.file.name

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(File, self).delete(*args, **kwargs)

    def get_name(self):
        name = re.sub(r'^.*/', '', self.file.name)
        if len(name) > 20:  # pragma: nocover
            name = name[:10] + "..." + name[-7:]
        return name


@python_2_unicode_compatible
class Invitation(models.Model):
    """
    User invitation to contribute to a project.

    :project: Related project.
    :user: Connected user account.
    :email: Email of the invited person.
    :first_name: Optional first name of the invited person.
    :last_name: Optional last name of the invited person.
    :status: Status of the invitation.
    """
    project = models.ForeignKey(
        'projects.Project',
        verbose_name=_('Project'),
        related_name='invitations',
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('User'),
        related_name='invitations',
        blank=True, null=True,
    )

    email = models.EmailField(
        verbose_name=_('Email'),
    )

    first_name = models.CharField(
        max_length=256,
        verbose_name=_('First name'),
        blank=True,
    )

    last_name = models.CharField(
        max_length=256,
        verbose_name=_('Last name'),
        blank=True,
    )

    status = models.CharField(
        max_length=50,
        verbose_name=_('Status'),
        choices=(
            ('pending', _('Pending')),
            ('accepted', _('Accepted')),
            ('declined', _('Declined')),
        ),
        default='pending',
    )

    class Meta:
        verbose_name = _('Invitation')
        verbose_name_plural = _('Invitations')
        ordering = ['email']

    def __str__(self):
        return self.email


@python_2_unicode_compatible
class Label(models.Model):
    """
    Label, which can be used to label a document.

    :name: Name of the label.
    :project: Project, the label should be assigned to.
    :colour: Colour of the label.
    """
    name = models.CharField(
        max_length=56,
        verbose_name=_('Name'),
    )

    project = models.ForeignKey(
        'projects.Project',
        verbose_name=_('Project'),
        related_name='labels',
    )

    colour = models.CharField(
        verbose_name=_('Colour'),
        max_length=7,
    )

    class Meta:
        verbose_name = _('Label')
        verbose_name_plural = _('Labels')
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.colour:
            colours = {
                'antiquewhite': '#FAEBD7',
                'aqua': '#00FFFF',
                'aquamarine': '#7FFFD4',
                'azure': '#F0FFFF',
                'beige': '#F5F5DC',
                'bisque': '#FFE4C4',
                'black': '#000000',
                'blanchedalmond': '#FFEBCD',
                'blue': '#0000FF',
                'blueviolet': '#8A2BE2',
                'brown': '#A52A2A',
                'burlywood': '#DEB887',
                'cadetblue': '#5F9EA0',
                'chartreuse': '#7FFF00',
                'chocolate': '#D2691E',
                'coral': '#FF7F50',
                'cornflowerblue': '#6495ED',
                'cornsilk': '#FFF8DC',
                'crimson': '#DC143C',
                'cyan': '#00FFFF',
                'darkblue': '#00008B',
                'darkcyan': '#008B8B',
                'darkgoldenrod': '#B8860B',
                'darkgray': '#A9A9A9',
                'darkgreen': '#006400',
                'darkkhaki': '#BDB76B',
                'darkmagenta': '#8B008B',
                'darkolivegreen': '#556B2F',
                'darkorange': '#FF8C00',
                'darkorchid': '#9932CC',
                'darkred': '#8B0000',
                'darksalmon': '#E9967A',
                'darkseagreen': '#8FBC8F',
                'darkslateblue': '#483D8B',
                'darkslategray': '#2F4F4F',
                'darkturquoise': '#00CED1',
                'darkviolet': '#9400D3',
                'deeppink': '#FF1493',
                'deepskyblue': '#00BFFF',
                'dimgray': '#696969',
                'dodgerblue': '#1E90FF',
                'firebrick': '#B22222',
                'floralwhite': '#FFFAF0',
                'forestgreen': '#228B22',
                'fuchsia': '#FF00FF',
                'gainsboro': '#DCDCDC',
                'ghostwhite': '#F8F8FF',
                'gold': '#FFD700',
                'goldenrod': '#DAA520',
                'gray': '#808080',
                'green': '#008000',
                'greenyellow': '#ADFF2F',
                'honeydew': '#F0FFF0',
                'hotpink': '#FF69B4',
                'indianred': '#CD5C5C',
                'indigo': '#4B0082',
                'ivory': '#FFFFF0',
                'khaki': '#F0E68C',
                'lavender': '#E6E6FA',
                'lavenderblush': '#FFF0F5',
                'lawngreen': '#7CFC00',
                'lemonchiffon': '#FFFACD',
                'lightblue': '#ADD8E6',
                'lightcoral': '#F08080',
                'lightcyan': '#E0FFFF',
                'lightgoldenrodyellow': '#FAFAD2',
                'lightgreen': '#90EE90',
                'lightgray': '#D3D3D3',
                'lightpink': '#FFB6C1',
                'lightsalmon': '#FFA07A',
                'lightseagreen': '#20B2AA',
                'lightskyblue': '#87CEFA',
                'lightslategray': '#778899',
                'lightsteelblue': '#B0C4DE',
                'lightyellow': '#FFFFE0',
                'lime': '#00FF00',
                'limegreen': '#32CD32',
                'linen': '#FAF0E6',
                'magenta': '#FF00FF',
                'maroon': '#800000',
                'mediumaquamarine': '#66CDAA',
                'mediumblue': '#0000CD',
                'mediumorchid': '#BA55D3',
                'mediumpurple': '#9370DB',
                'mediumseagreen': '#3CB371',
                'mediumslateblue': '#7B68EE',
                'mediumspringgreen': '#00FA9A',
                'mediumturquoise': '#48D1CC',
                'mediumvioletred': '#C71585',
                'midnightblue': '#191970',
                'mintcream': '#F5FFFA',
                'mistyrose': '#FFE4E1',
                'moccasin': '#FFE4B5',
                'navajowhite': '#FFDEAD',
                'navy': '#000080',
                'oldlace': '#FDF5E6',
                'olive': '#808000',
                'olivedrab': '#6B8E23',
                'orange': '#FFA500',
                'orangered': '#FF4500',
                'orchid': '#DA70D6',
                'palegoldenrod': '#EEE8AA',
                'palegreen': '#98FB98',
                'paleturquoise': '#AFEEEE',
                'palevioletred': '#DB7093',
                'papayawhip': '#FFEFD5',
                'peachpuff': '#FFDAB9',
                'peru': '#CD853F',
                'pink': '#FFC0CB',
                'plum': '#DDA0DD',
                'powderblue': '#B0E0E6',
                'purple': '#800080',
                'red': '#FF0000',
                'rosybrown': '#BC8F8F',
                'royalblue': '#4169E1',
                'saddlebrown': '#8B4513',
                'salmon': '#FA8072',
                'sandybrown': '#FAA460',
                'seagreen': '#2E8B57',

annotate/projects/forms.py
"""Forms for the projects app."""
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import ugettext_lazy as _

from . import models


class ProjectForm(forms.ModelForm):
    class Meta:
        fields = ['name']
        model = models.Project

    def __init__(self, owner, *args, **kwargs):
        self.owner = owner
        super(ProjectForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.owner = self.owner
        return super(ProjectForm, self).save(*args, **kwargs)


class ProjectInfoForm(forms.ModelForm):
    class Meta:
        fields = ['type', 'deadline', 'purpose']
        model = models.Project
        widgets = {
            'deadline': forms.SelectDateWidget(attrs={
                'style': 'display: inline-block; width: 70px;'}),
        }


class FileForm(forms.ModelForm):
    class Meta:
        fields = ['file']
        model = models.File

    def __init__(self, project, *args, **kwargs):
        self.project = project
        super(FileForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.project = self.project
        return super(FileForm, self).save(*args, **kwargs)


class InvitationForm(forms.ModelForm):
    class Meta:
        fields = ['email', 'first_name', 'last_name']
        model = models.Invitation

    def __init__(self, project, *args, **kwargs):
        self.project = project
        super(InvitationForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and self.project.invitations.filter(email=email):
            raise forms.ValidationError(
                _('You\'ve already invited this user.'))
        if email and email == self.project.owner.email:
            raise forms.ValidationError(
                _('You cannot invite yourself.'))
        return email

    def save(self, *args, **kwargs):
        self.instance.project = self.project
        User = get_user_model()
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except User.DoesNotExist:
            pass
        else:
            self.instance.user = user
        return super(InvitationForm, self).save(*args, **kwargs)


class LabelForm(forms.ModelForm):
    class Meta:
        fields = ['name']
        model = models.Label

    def __init__(self, project, *args, **kwargs):
        self.project = project
        super(LabelForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if self.project.labels.exclude(pk=self.instance.pk).filter(name=name):
            raise forms.ValidationError(_('Label already exists.'))
        return name

    def save(self, *args, **kwargs):
        if not self.instance.pk:
            self.instance.project = self.project
        return super(LabelForm, self).save(*args, **kwargs)

annotate/projects/templates/projects/file_detail.html
{% extends "projects/project_detail.html" %}
{% load i18n annotate_tags libs_tags %}

{% block head_title %}{% blocktrans with name=object.get_name %}Labelling {{ name }}{% endblocktrans %}{% endblock %}

{% block top %}
  {% if request.user != object.project.owner %}
    <small>{% blocktrans with owner=object.project.owner name=object.get_name type=object.project.get_type_display %}Helping {{ owner }} with {{ name }} on {{ type }}{% endblocktrans %}</small>
  {% endif %}
{% endblock %}

{% block left %}
  {% csrf_token %}
  {% if object.project.labels.all %}
    <h4>{% trans "Select a label" %}</h4>
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="label-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <div class="label-colour" style="background: {{ object.project.labels.all.0.colour }};"></div>{{ object.project.labels.all.0.name }}
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="label-dropdown" style="height:250px;overflow:auto;">
        {% for label in object.project.labels.all %}
          <li {% if forloop.first %}class="disabled"{% endif %}><a href="#" data-label-pk="{{ label.pk }}" data-class="change-label"><div class="label-colour" style="background: {{ label.colour }}"></div>{{ label.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}
{% endblock %}

{% block content %}
  {% get_user_name object.project.owner as owner %}
  <h2 style="margin-top: 0;">{% blocktrans with owner=owner name=object.get_name type=object.project.get_type_display %}Labelling {{ name }}{% endblocktrans %}  <small><a href="{% url "project_detail" pk=object.project.pk %}">{% trans "back" %}</a></small></h2>
  {% if object.project.labels.all %}
    <div data-id="scope" id="scope">
      {% if sentences %}
        <svg xmlns="http://www.w3.org/2000/svg">
            <defs>
                {% for label in object.project.labels.all %}
                  <marker id="arrow-point-{{ label.pk }}" style="fill: {{ label.colour }};" markerWidth="10" markerHeight="10" refx="3" refy="6" orient="auto" class="arrow-point{% if forloop.first %} selected{% endif %}" data-name="{{ label.name }}" data-create-url="{% url "annotation_create" file_pk=object.pk label_pk=label.pk %}">
                      <path d="M2,1 L2,10 L10,6 L2,2" />
                  </marker>
                {% endfor %}
            </defs>
        </svg>
        <div class="sentences">
          {% for sentence in sentences %}
            {% set_context forloop.counter as sentence_counter %}
            <div class="sentence {% cycle 'odd' 'even' %} sentence-id-{{ sentence_counter }}" data-sentence-id="{{ sentence_counter }}" data-annotations="{{ sentence.annotations }}">
              {% for word in sentence.tokens %}
                <div class="rich-token rich-token-{{ sentence_counter }}-{{ forloop.counter }} eo-S{{ sentence_counter }}T{{ forloop.counter }}" data-id="S{{ sentence_counter }}T{{ forloop.counter }}" data-class="word" data-position="{{ forloop.counter }}">
                  <span class="token">{{ word }}</span>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  {% else %}
    <em>{% trans "The project owner hasn't added any labels yet." %}</em>
  {% endif %}
{% endblock %}

annotate/projects/templates/projects/invitation_form.html
{% extends "projects/project_detail.html" %}
{% load i18n libs_tags project_tags %}

{% block head_title %}{% blocktrans with name=project.name %}Invitations for {{ name }}{% endblocktrans %}{% endblock %}

{% block content %}
  <div style="margin-top: 0;" class="page-header">
    <h2 style="margin-top: 0;">{% trans "Invite labellers" %}</h2>
  </div>
  <form method="post" action=".">
    {% include "django_libs/partials/form.html" %}
    <div style="margin-top: 10px;">
      <input class="btn btn-success" type="submit" value="{% trans "Send invitation" %}" />
    </div>
  </form>
  {% if project.invitations.all %}
    <table class="table" style="margin-top: 30px;">
      <thead>
        <tr>
          <th>{% trans "Email" %}</th>
          <th>{% trans "First name" %}</th>
          <th>{% trans "Last name" %}</th>
          <th>{% trans "Registered" %}</th>
          <th>{% trans "Status" %}</th>
        </tr>
      </thead>
      {% for invitation in project.invitations.all %}
        <tr>
          <td>{{ invitation.email }}</td>
          <td>{{ invitation.first_name }}</td>
          <td>{{ invitation.last_name }}</td>
          <td><span class="glyphicon glyphicon-{% if invitation.user %}ok{% else %}remove{% endif %}"></span></td>
          <td class="text-{% if invitation.status == 'accepted' %}success{% elif invitation.status == 'declined' %}danger{% endif %}">{{ invitation.get_status_display }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}

annotate/projects/templates/projects/label_confirm_delete.html
{% extends "projects/project_detail.html" %}
{% load i18n %}

{% block head_title %}{% blocktrans with name=label.name %}Delete {{ name }}{% endblocktrans %}{% endblock %}

{% block content %}
  <div style="margin-top: 0;" class="page-header">
    <h2 style="margin-top: 0;">{% blocktrans with name=label.name %}Delete {{ name }}{% endblocktrans %}</h2>
  </div>
  <form method="post" action=".">
    <p>{% trans "Are you sure to delete this label?" %}</p>
    {% include "django_libs/partials/form.html" %}
    <div style="margin-top: 10px;">
      <input class="btn btn-danger" type="submit" value="{% trans "Confirm" %}" />
    </div>
  </form>
{% endblock %}

annotate/projects/templates/projects/project_detail.html
{% extends "base.html" %}
{% load i18n libs_tags project_tags %}

{% block head_title %}{{ project.name }}{% endblock %}

{% block main %}
  {% block top %}{% endblock %}
  <div class="row">
    <div class="col-sm-4">
      <div data-affix="true">
        <div class="panel panel-default" style="margin-bottom: 0;">
          <div class="panel-heading"><h3 class="panel-title"><a href="{% url "project_detail" pk=project.pk %}">{{ project.name }}</a></h3></div>
          <ul class="list-group">
            {% if project.deadline %}
              <li class="list-group-item">{% trans "Type" %}<span class="badge">{{ project.get_type_display }}</span></li>
            {% endif %}
            {% if project.deadline %}
              <li class="list-group-item">{% trans "Purpose" %}<span class="badge">{{ project.get_purpose_display }}</span></li>
            {% endif %}
            {% if project.deadline %}
              <li class="list-group-item">{% trans "Deadline" %}<span class="badge">{{ project.deadline|date }}</span></li>
            {% endif %}
            <li class="list-group-item">{% trans "Owner" %}<span class="badge">{{ project.owner.email }}</span></li>
            {% if project.deadline %}
              <li class="list-group-item"><small>{{ project.description|linebreaks }}</small></li>
            {% endif %}
          </ul>
          {% if not hide_label_forms and request.user == project.owner %}
            <form data-class="label-form" action="." method="post" style="height:250px;overflow:auto;">
              {% csrf_token %}
              <div class="panel-body">
                {% for label in project.labels.all %}
                  {% include "projects/label_form.html" with label=label %}
                {% endfor %}
                {% include "projects/label_form.html" with project=project %}
              </div>
            </form>
          {% endif %}
          {% if request.user == project.owner %}
            <div class="panel-footer">
              <a class="btn btn-info" href="{% url "project_info" pk=project.pk %}">{% trans "Update" %}</a>
              <a class="btn btn-primary" href="{% url "project_detail" pk=project.pk %}">{% trans "Files & Labels" %}</a>
              <a class="btn btn-default" href="{% url "invitation_create" project_pk=project.pk %}">{% trans "Invite labellers" %}</a>
            </div>
          {% endif %}
        </div>

        {% block left %}{% endblock %}
      </div>
    </div>
    <div class="col-sm-8">
      {% block content %}
        {% if request.user == project.owner %}
          <!-- The file upload form used as target for the file upload widget -->
          <form id="fileupload" data-json-url="{% url "file_json" pk=project.pk %}" method="post" action="{% url "file_create" project_pk=project.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Redirect browsers with JavaScript disabled to the origin page -->
            <!--<noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>-->
            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
            <div class="fileupload-buttonbar">
              <p class="lead">{% trans "Drag & drop your files here." %}</p>
              <!-- The fileinput-button span is used to style the file input field as button -->
              <span class="btn btn-success fileinput-button">
                <span>{% trans "Add file(s)" %}</span>
                <input type="file" name="file" multiple>
              </span>
              <!-- The loading indicator is shown during file processing -->
              <span class="fileupload-loading"></span>
              {% comment %}
                <!-- The global progress information -->
                <div class="fileupload-progress pull-right">
                  <!-- The global progress bar -->
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                  </div>
                  <!-- The extended global progress information -->
                  <div class="progress-extended">&nbsp;</div>
                </div>
              {% endcomment %}
            </div>
            <!-- The table listing the files available for upload/download -->
            <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
          </form>
        {% else %}
          <div style="margin-top: 0;" class="page-header">
            <h2 style="margin-top: 0;">{% trans "Files" %}</h2>
          </div>
          {% if project.files.all %}
            <table role="presentation" class="table table-striped">
              <tbody>
                {% for file in project.files.all %}
                  <tr>
                    <td>
                      <p class="name">
                        <a href="{{ file.file.url }}" title="{{ file.get_name }}" download="{{ file.get_name }}">{{ file.get_name }}</a>
                      </p>
                    </td>
                    <td>
                      <span class="size">{{ file.file.size|filesizeformat }}</span>
                    </td>
                    <td class="text-right">
                      <a class="btn btn-warning" href="{% url "file_label" pk=file.pk %}">
                        <span>{% trans "Start labelling" %}</span>
                      </a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <em>{% trans "The project owner hasn't added any files yet. Please stand by." %}</em>
          {% endif %}
        {% endif %}
      {% endblock %}
    </div>
  </div>
  {% upload_js %}
{% endblock %}